### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by duramato** [cdiener/pyart#1]
When trying to run it im getting 

```
Traceback (most recent call last):
  File "./asciinator.py", line 45, in <module>
    img = np.sum( np.asarray( img.resize(S) ), axis=2)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1325, in resize
    return self.convert('RGBa').resize(size, resample).convert('RGBA')
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1334, in resize
    im = self.im.resize(size, resample)
TypeError: integer argument expected, got float
```

This happens both with a png or a jpeg

**Comment by cdiener** [comment]
Ok looking into it. The problem seems to be that round actually returns a float, not an int. Surprising that worked with Python 3...

**Comment by cdiener** [comment]
Okay, should work now...
